name: lpmi_premium_3
description: "Explore, enjoy, and personalize your favorite song collections! SongBook offers an organized library of song lyrics, customizable settings, and a beautiful interface."

publish_to: 'none'  # Prevent accidental publication to pub.dev

version: 1.6.0+6

environment:
  sdk: ">=2.17.0 <4.0.0"  # Updated for better compatibility

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  
  # Permissions
  permission_handler: ^12.0.0+1
  
  # Localization
  flutter_localizations:
    sdk: flutter
    
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.0
  flutter_animate: ^4.3.0
  
  # Utilities
  intl: ^0.19.0
  share_plus: ^11.0.0
  url_launcher: ^6.2.3
  package_info_plus: ^8.3.0
  fluttertoast: ^8.2.4
  
  # Storage & Data
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  path_provider_android: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network & Caching
  http: ^1.1.2
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  connectivity_plus: ^6.1.4
  
  # Media & Audio
  audioplayers: ^6.4.0
  image_picker: ^1.0.7
  flutter_plugin_android_lifecycle: ^2.0.17
  
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  equatable: ^2.0.5
  
  # Fonts & Styling
  google_fonts: ^6.1.0
  
  # Other Features
  flutter_blue_plus: ^1.5.3
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # Fixed path
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"  # Fixed path

flutter:
  uses-material-design: true  # This enables Material Icons

  assets:
    - assets/data/lpmi.json
    - assets/data/srd.json
    - assets/data/song_list.json
    - assets/images/
    - assets/images/header_image.png
    - assets/images/app_icon.png
    - assets/images/music_note.gif  # Fixed typo
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400