name: lpmi_premium_3
description: "Explore, enjoy, and personalize your favorite song collections! SongBook offers an organized library of song lyrics, customizable settings, and a beautiful interface."

publish_to: 'none'  # Prevent accidental publication to pub.dev

version: 1.6.0+6

environment:
  sdk: ">=2.17.0 <3.0.0"  # Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  permission_handler: ^11.3.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_speed_dial: ^7.0.0
  intl: ^0.19.0
  share_plus: ^10.0.3
  shared_preferences: ^2.0.13
  path_provider: ^2.0.12
  path_provider_android: ^2.0.11
  http: ^1.2.2
  rxdart: ^0.28.0
  audioplayers: ^6.1.0
  flutter_slidable: ^4.0.0
  provider: ^6.0.5     # State management
  cached_network_image: ^3.3.0  # Improved image caching
  flutter_blue_plus: ^1.10.2  # Bluetooth functionality
  fluttertoast: ^8.2.2  # Toast notifications
  url_launcher: ^6.1.11  # Launch URLs
  flutter_cache_manager: ^3.3.1  # Cache management
  hive: ^2.2.3  # Local database
  hive_flutter: ^1.1.0  # Flutter integration for Hive
  connectivity_plus: ^6.1.3  # Network connectivity
  equatable: ^2.0.5  # Equality comparison
  flutter_bloc: ^9.1.0  # BLoC state management
  google_fonts: ^6.2.1  # Custom fonts from Google Fonts
  flutter_spinkit: ^5.1.0  # Loading animations
  package_info_plus: ^8.3.0  # App package information
  flutter_native_splash: ^2.2.19  # Custom splash screen
  flutter_animate: ^4.1.1  # Animation utilities
  image_picker: ^1.0.7  # Use the latest version
  flutter_local_notifications: ^14.1.1  # For local notifications
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  hive_generator: ^2.0.1  # Hive code generation
  build_runner: ^2.3.3  # Code generation runner

# The rest of your configuration remains unchanged
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/lpmi.json
    - assets/srd.json
    - assets/header_image.png
    - assets/app_icon.png
    - assets/song_list.json
    - assets/music_note.gif

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic