name: lpmi_premium
description: A Flutter project for LPMI Premium song collection app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.6
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^3.1.1
  
  # Utilities
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  
  # Audio
  audioplayers: ^6.1.0
  
  # HTTP & Networking
  http: ^1.2.2
  
  # Fonts
  google_fonts: ^6.2.1
  
  # Package Info
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/
    - shaders/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700